"""
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-4oIxtIp_MWcd3YZSL3d28WtFAQ9U6Ok

"""

""" 
This code uses YOLO v5 to detect tumour in the MRI scanned images. 
The code was run in Google Colab notebook for high speed GPU access.
It is recommended to upload the 'archive_yolo.zip' dataset file to Google drive before code execution.

"""

""" The YOLO v5 Github repository is cloned to the notebook """

!git clone https://github.com/ultralytics/yolov5  # repository cloning
%cd yolov5
%pip install -qr requirements.txt # all required dependencies installed

"""The required libraries are imported"""

import torch  # To run YOLO v5 algorithm
import os
import glob
from IPython.display import Image, display  # To display the images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

"""The dataset is imported from the Google Drive"""

from google.colab import drive 
drive.mount('/content/drive') # Google drive is mounted

# The dataset file is unzipped for use (Change the directory path according to the dataset directory)
!unzip /content/drive/MyDrive/AAIMLDS/Datasets/Brain_tumor/archive_yolo.zip -d /content/drive/MyDrive/AAIMLDS/Datasets/Brain_tumor/

"""Model is Trained using yolov5s.pt weight"""

# Training of model for 100 epochs (Change the directory path according to the dataset directory)
!python train.py --img 320 --batch 16 --epochs 100 --data /content/drive/MyDrive/AAIMLDS/Datasets/Brain_tumor/archive_yolo/tumor.yaml --weights yolov5s.pt --cache

"""Model Evaluation using Tensorboard"""


# Evaluation Metrics like Mean Average Precision is visualized
%load_ext tensorboard
%tensorboard --logdir runs

"""Model Prediction"""

# Model is predicted using the best weights of the trained model (Change the directory path according to the weight and dataset directory)
!python detect.py --weights runs/train/exp10/weights/best.pt --img 320 --conf 0.1 --source /content/drive/MyDrive/AAIMLDS/Datasets/Brain_tumor/archive_yolo/images/Test

# Examples of tumour prediction according to their types
for imageName in glob.glob('/content/yolov5/runs/detect/exp3/*.jpg'): # Iterated through test data
    display(Image(filename=imageName))
    print("\n")

"""Saving the model weight for future use"""

from google.colab import files
files.download('./runs/train/exp10/weights/best.pt')

# % References %

# 1. YOLO v5 Github repository for training of custom data. https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb.

# 2. DeepLearning Youtube channel. YOLOv5 training with custom data.

# 3. Nicholas Renotte Youtube channel. Deep Drowsiness Detection using YOLO, Pytorch and Python.